services:
  - type: web
    name: fraud-detection-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    branch: main
    autoDeploy: true